### ISSUE TITLE
1

### ISSUE THREAD

**Issue by thenormtema** [Costello1329/java-hse-2021#2]

**Comment by Costello1329** [comment]
?

**Comment by bigser91** [comment]
Здравствуйте, да, я подписан на эту беседу. Бекжан с БИ-212 группы

Hello, yes, I am subscribed to this conversation.  Bekzhan with BI-212 group

Вт, 16 нояб. 2021 г. в 17:30, Konstantin Leladze ***@***.***>:

**Comment by bigser91** [comment]
Cool, thanks!

Вт, 16 нояб. 2021 г. в 17:34, Konstantin Leladze ***@***.***>:
